spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AcademicSys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: SE
    password: se123456

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

